export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const SOURCE_UPDATE = 'SOURCE_UPDATE'
export const DESTINATION_UPDATE = 'DESTINATION_UPDATE'
export const JOURNEY_DATE_UPDATE = 'JOURNEY_DATE_UPDATE'

export const SEARCH_BUSES_START = 'SEARCH_BUSES_START'
export const SEARCH_BUSES_SUCCESS = 'SEARCH_BUSES_SUCCESS'
export const SEARCH_BUSES_FAIL = 'SEARCH_BUSES_FAIL'

export const FETCH_BOOKINGS_START = 'FETCH_BOOKINGS_START'
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS'
export const FETCH_BOOKINGS_FAIL = 'FETCH_BOOKINGS_FAIL'

export const BOOKING_START = 'BOOKING_START'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'
export const BOOKING_INIT = 'BOOKING_INIT'